"""add_crm_tables

Revision ID: 701522b5add7
Revises: ee24f87bfa9c
Create Date: 2026-08-20 19:30:54.059126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '701522b5add7'
down_revision: Union[str, None] = 'ee24f87bfa9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('free', 'starter', 'growth', 'scale', name='plan_tier').create(op.get_bind())
    sa.Enum('call', 'note', 'email', 'meeting', 'task', 'stage_change', name='crm_activity_type').create(op.get_bind())
    sa.Enum('open', 'won', 'lost', name='deal_status').create(op.get_bind())
    sa.Enum('lead', 'mql', 'sql', 'opportunity', 'customer', name='contact_lifecycle_stage').create(op.get_bind())
    sa.Enum('manual', 'csv', 'call', 'api', 'integration', name='contact_source').create(op.get_bind())
    op.create_table('crm_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_crm_tags_org_name')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan', postgresql.ENUM('free', 'starter', 'growth', 'scale', name='plan_tier', create_type=False), server_default=sa.text("'free'::plan_tier"), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('seats', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index('ix_subscriptions_org_id', 'subscriptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_companies_org_name')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index('ix_companies_org_id', 'companies', ['organization_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('source', postgresql.ENUM('manual', 'csv', 'call', 'api', 'integration', name='contact_source', create_type=False), server_default=sa.text("'manual'::contact_source"), nullable=False),
    sa.Column('lifecycle_stage', postgresql.ENUM('lead', 'mql', 'sql', 'opportunity', 'customer', name='contact_lifecycle_stage', create_type=False), server_default=sa.text("'lead'::contact_lifecycle_stage"), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('do_not_call', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index('ix_contacts_org_id', 'contacts', ['organization_id'], unique=False)
    op.create_index('ix_contacts_org_phone', 'contacts', ['organization_id', 'phone'], unique=False)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_index('uq_contacts_org_phone', 'contacts', ['organization_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('contact_tags',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['crm_tags.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'tag_id')
    )
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pipeline', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'won', 'lost', name='deal_status', create_type=False), server_default=sa.text("'open'::deal_status"), nullable=False),
    sa.Column('lost_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deals_contact_id', 'deals', ['contact_id'], unique=False)
    op.create_index('ix_deals_org_id', 'deals', ['organization_id'], unique=False)
    op.create_index('ix_deals_org_status_stage', 'deals', ['organization_id', 'status', 'stage'], unique=False)
    op.create_table('crm_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('type', postgresql.ENUM('call', 'note', 'email', 'meeting', 'task', 'stage_change', name='crm_activity_type', create_type=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('workflow_run_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crm_activities_contact_created', 'crm_activities', ['contact_id', 'created_at'], unique=False)
    op.create_index('ix_crm_activities_open_tasks', 'crm_activities', ['organization_id', 'due_at'], unique=False, postgresql_where=sa.text("type = 'task' AND completed_at IS NULL"))
    op.create_index('ix_crm_activities_org_id', 'crm_activities', ['organization_id'], unique=False)
    op.create_index('uq_crm_activities_run_call', 'crm_activities', ['workflow_run_id'], unique=True, postgresql_where=sa.text("type = 'call' AND workflow_run_id IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_crm_activities_run_call', table_name='crm_activities', postgresql_where=sa.text("type = 'call' AND workflow_run_id IS NOT NULL"))
    op.drop_index('ix_crm_activities_org_id', table_name='crm_activities')
    op.drop_index('ix_crm_activities_open_tasks', table_name='crm_activities', postgresql_where=sa.text("type = 'task' AND completed_at IS NULL"))
    op.drop_index('ix_crm_activities_contact_created', table_name='crm_activities')
    op.drop_table('crm_activities')
    op.drop_index('ix_deals_org_status_stage', table_name='deals')
    op.drop_index('ix_deals_org_id', table_name='deals')
    op.drop_index('ix_deals_contact_id', table_name='deals')
    op.drop_table('deals')
    op.drop_table('contact_tags')
    op.drop_index('uq_contacts_org_phone', table_name='contacts', postgresql_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index('ix_contacts_org_phone', table_name='contacts')
    op.drop_index('ix_contacts_org_id', table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_companies_org_id', table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_org_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('crm_tags')
    sa.Enum('manual', 'csv', 'call', 'api', 'integration', name='contact_source').drop(op.get_bind())
    sa.Enum('lead', 'mql', 'sql', 'opportunity', 'customer', name='contact_lifecycle_stage').drop(op.get_bind())
    sa.Enum('open', 'won', 'lost', name='deal_status').drop(op.get_bind())
    sa.Enum('call', 'note', 'email', 'meeting', 'task', 'stage_change', name='crm_activity_type').drop(op.get_bind())
    sa.Enum('free', 'starter', 'growth', 'scale', name='plan_tier').drop(op.get_bind())
    # ### end Alembic commands ###
